name: nextflow_pipeline

channels:
  - conda-forge
  - bioconda

dependencies:
  - nextflow=24.10.6
  - fastqc=0.12.1
  - cutadapt=5.2
  - bwa=0.7.17
  - samtools=1.21
  - bcftools=1.21
  - multiqc=1.18